package com.conns.marketing.campaign.model;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "dev_MMCS_CustomerMDM")
public class Customer {
	private String postalCode;
	private String uniqueCID;
	private List<CustomerAddress> address;
	private String createdDate;
	private String dateOfBirth;
	private String emailAddress;
	private String firstName;
	private String lastName;
	
	@DynamoDBHashKey(attributeName = "postalCode")
	public String getPostalCode() {
		return postalCode;
	}
	
	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}
	
	@DynamoDBAttribute(attributeName = "uniqueCID")
	public String getUniqueCID() {
		return uniqueCID;
	}
	
	public void setUniqueCID(String uniqueCID) {
		this.uniqueCID = uniqueCID;
	}

	@DynamoDBAutoGeneratedTimestamp
	@DynamoDBAttribute(attributeName = "createdDate")
	public String getCreatedDate() {
		return createdDate;
	}
	
	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}
	
	@DynamoDBAttribute(attributeName = "dateOfBirth")
	public String getDateOfBirth() {
		return dateOfBirth;
	}
	
	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	
	@DynamoDBAttribute(attributeName = "emailAddress")
	public String getEmailAddress() {
		return emailAddress;
	}
	
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}
	
	@DynamoDBAttribute(attributeName = "firstName")
	public String getFirstName() {
		return firstName;
	}
	
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@DynamoDBAttribute(attributeName = "lastName")
	public String getLastName() {
		return lastName;
	}
	
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@DynamoDBAttribute(attributeName = "address")
	public List<CustomerAddress> getAddress() {
		return address;
	}

	public void setAddress(List<CustomerAddress> address) {
		this.address = address;
	}

}
